# Generated by Django 4.1.4 on 2022-12-25 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDeveloper',
            fields=[
                ('name_company', models.TextField(primary_key=True, serialize=False)),
                ('adress_main_office', models.TextField(blank=True, null=True)),
                ('hotline_phone_number', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id_building', models.AutoField(primary_key=True, serialize=False)),
                ('adress_building', models.TextField(blank=True, null=True)),
                ('type_building', models.TextField(blank=True, null=True)),
                ('name_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.propertydeveloper')),
            ],
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id_builder', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('id_building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.building')),
            ],
        ),
    ]
