# Generated by Django 4.1.4 on 2022-12-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builder',
            old_name='building_id',
            new_name='building',
        ),
        migrations.RemoveField(
            model_name='building',
            name='name_company',
        ),
        migrations.AddField(
            model_name='building',
            name='property_developer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.property_developer'),
            preserve_default=False,
        ),
    ]
