# Generated by Django 4.1.4 on 2022-12-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_builder_building_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builder',
            name='building',
        ),
        migrations.RemoveField(
            model_name='building',
            name='property_developer',
        ),
        migrations.AddField(
            model_name='builder',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='name_company',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='builder',
            name='builder_id',
            field=models.IntegerField(),
        ),
    ]
